### ISSUE TITLE
CDATA isn't parsed

### ISSUE THREAD

**Issue by pjeby** [freshe/poddl#10]
See e.g. the output of `poddl https://anchor.fm/s/1d5f5088/podcast/rss /tmp -l`, which looks like this:

```
[242] ![CDATA[#242 - 9 Ways to Increase Show Up Rate]]
[243] ![CDATA[#243 - Why All-In-One Tech Platforms are Dangerous]]
[244] ![CDATA[#244 - 3 More Ways to Increase Show Up Rate]]
[245] ![CDATA[#245 - Watch Me Pitch Live]]
```

In XML `<![CDATA[...]]>` is an escape to allow any characters other than `]]>` to be included without escaping; it appears poddl doesn't parse this and so ends up including it in the episode names (and resulting filenames).

**Comment by freshe** [comment]
Thanks! I've never come across a feed with CDATA in the titles. I will have to take a look at this.

**Comment by freshe** [comment]
This should now be fixed. New binaries uploaded

**Comment by pjeby** [comment]
Yep, works great.  Thanks!

**Comment by freshe** [comment]
👍
