### ISSUE TITLE
prepend numbers with 0 for better fs alignment

### ISSUE THREAD

**Issue by kimusan** [freshe/poddl#12]
Some simple music players will sort the files according to naming. This means the files will be ordered like 1, 10, 11, 12....19, 2, 20, 21.... 

By padding with 0 in front of the numbers up to the length of the highest number of items in the podcast, then it will prevent this broken ordering. 
If podcast has 120 episodes:
001, 002, ....010, 011, ....100, 101... 120

Should be a quick fix as you have the number of items in the podcast and the number you are working on.

**Comment by kimusan** [comment]
Added PR for the fix. tested it on ubuntu (WLS2 with ubuntu actually). 

It would be a good idea to have a makefile for building this project (I can add the one I had to make when testing this).

**Comment by freshe** [comment]
Fixed by 1450536
