### ISSUE TITLE
Wrong episode numbering?

### ISSUE THREAD

**Issue by scollovati** [freshe/poddl#16]
Hi,
I don't understand why poddl for win x64 does not list and download with the correct numbering [this podcast](https://d172q3toj7w1md.cloudfront.net/rss-xml-files/e85c6ddf-903d-4245-a21d-d8606351b0ae.xml).

The items are ordered by date ascending (oldest first), but they get listed in the opposite order even when using the `-r`  argument.

**Comment by freshe** [comment]
Thanks, will look into it

**Comment by freshe** [comment]
This should be fixed now — taking \<pubdate\> into account 🤞 New binaries uploaded

**Comment by scollovati** [comment]
Perfect, thanks!
