### ISSUE TITLE
Windows Defender detected virus in Win64 version

### ISSUE THREAD

**Issue by abrothman-vacatia** [freshe/poddl#17]
Trojan:Win32/Wacatac.H!ml

![image](https://github.com/freshe/poddl/assets/114940610/9946acf6-0b35-47c7-8a89-e40d558bc773)

**Comment by freshe** [comment]
Thanks, this is a false positive reported by Windows Defender.. I will try to recompile the Windows binaries on another system

**Comment by Paulladium46** [comment]
@freshe 
Malwarebytes quarantines the software and virtustotal flags the exe as malicious.

![image](https://github.com/freshe/poddl/assets/44069000/552a3d59-9729-490e-9d29-26e1a5c8beef)

**Comment by freshe** [comment]
Thanks, I really don't know what to do about malware/virus false positives on Windows. Suggestions are welcome.

**Comment by Paulladium46** [comment]
Good to see that with your updates yesterday that VirusTotal is not flagging it any longer.
The ARM version does have a couple flags in VT, just so you know.

I'm updating my sandbox system to see how it looks in Malwarebytes now...

**Comment by Paulladium46** [comment]
and BTW - very nice little handy tool!

**Comment by freshe** [comment]
Great! Thanks for checking

**Comment by Paulladium46** [comment]
I'm not finding any further warnings with the windows x64 version from Windows Defender or from Malwarebytes.
I did test this in a new sandbox as well, so it would all be fresh.

Update the ARM64 and I think you can close this issue.

**Comment by freshe** [comment]
Thanks! The arm64 binary is updated. (I have a feeling the issue could re-appear if curl 8.6.0 gets flagged)
