### ISSUE TITLE
Invalid Response from URL

### ISSUE THREAD

**Issue by reidelkins** [freshe/poddl#18]
# Command and response
root@6e1626550a7c:/workspace/poddl# ./poddl http://www.secondfront.com/podcasts/rss.xml ./tmp        

poddl 2024.01.26
libcurl/8.4.0 mbedTLS/3.5.0

https://www.fredrikblank.com/poddl/

Fetching URL: http://www.secondfront.com/podcasts/rss.xml
Error: Invalid response from URL

# What I've Done
Download compiled source, unzipped and ran command
Have attempted with multiple urls to include
1. http://www.secondfront.com/podcasts/rss.xml
2. https://chinahistorypodcast.libsyn.com/rss
3. https://cowenconvos.libsyn.com/rss

Any ideas on what I am doing wrong?

**Comment by freshe** [comment]
Thanks!

Feed 1 has no ```<enclosure>``` tags in it. So maybe another format I need to support.
But feed 2 and 3 seems to work just fine 🤔

<img width="551" alt="Screenshot 2024-02-28 at 18 57 10" src="https://github.com/freshe/poddl/assets/6495600/89a4e8e1-e160-406c-a001-100d9b06b800">
