### ISSUE TITLE
Unable to parse URL contents as XML

### ISSUE THREAD

**Issue by Futureknows** [freshe/poddl#21]
Since there is no RPM binary, I installed poddl in Fedora from python [pip](https://pypi.org/project/poddl/):

`pip install poddl`

When I attempt to download any RSS feed, I get the error 
`Unable to parse URL contents as XML
`

**Comment by Futureknows** [comment]
I tried the Debian binary, it is working in Fedora.

**Comment by freshe** [comment]
Nice! just fyi, the python script is another project with the same name (sorry about that)
https://github.com/benkyriakou/poddl
