### ISSUE TITLE
Feature request: "Error downloading file": do something about it

### ISSUE THREAD

**Issue by eexexiexit** [freshe/poddl#3]
Sometimes, files are not fully downloaded. The download ends with "Error downloading file" and a partially downloaded file is saved. It would be nice if there was a way to

a) distinguish between fully and partially downloaded files (for instance by file name), so that users can decide if they want listen to incomplete episodes.
b) an option to retry download of partially downloaded files without overwriting fully downloaded files.

Example: LibsynDL https://chinahistorypodcast.libsyn.com/rss /tmp/

(less than half of the episodes where fully downloaded)

**Comment by freshe** [comment]
Thanks, will look into it

**Comment by freshe** [comment]
Commit a80a4e7142f2fea1ac89c1e46675f53f1dc89e23 hopefully solves the issue. Saves incomplete files in a temp directory + skips fully downloaded files
