### ISSUE TITLE
Patreon Support would be really cool too

### ISSUE THREAD

**Issue by gooseyman** [freshe/poddl#5]
Support for private Patreon RSS feeds would be awesome. I think the only thing that is hanging this up is the parsing of the URL.

I got in the water a little bit and tried but this is above my skillset. 

Here's an example of a Patreon enclosure url:

<enclosure url="https://patreonusercontent.com/3/patreon-media/p/post/path_to.mp3?token-time=123456789&token-hash=a_big_token_here_with_fun_characters" length="123456789" type="audio/mpeg"/>
<guid isPermaLink="false">123456789</guid>

**Comment by freshe** [comment]
Interesting, so the enclosure URL is just an ID? I might have to subscribe to a private feed to see how it works. Can you share what particular Patreon podcast/podcasts you subscribe to?

**Comment by gooseyman** [comment]
whoops - forgot to format correctly in my first post. 

Here's an example of a Patreon enclosure url:

`enclosure url="https://c10.patreonusercontent.com/4/patreon-media/p/post/75694065/e40fa1d27bce49f481e2700eade8b297/eyJhIjoxLCJwIjoxfQ%3D%3D/1.mp3?token-time=123456789&token-hash=a_big_token_here_with_fun_characters" length="88925505" type="audio/mpeg"/>`

**Comment by freshe** [comment]
Thanks! Turns out that the Patreon &token-hash parameter is HTML encoded (& amp;token-hash). Commit bd8cf0958920e89c3b15b2d12f5aaa7dc2a17d06 hopefully fixes that.

**Comment by gooseyman** [comment]
just tested and works great!

**Comment by freshe** [comment]
Splendid! Thanks
