### ISSUE TITLE
catchup podcasts

### ISSUE THREAD

**Issue by bennyrobinson** [freshe/poddl#6]
Love this app, best I have found so appreciate it thank you. 
Unsure if I am mentioning something someone else has before, but is there a way when running the app to skip podcasts already downloaded or present in a folder?

**Comment by freshe** [comment]
Happy to hear, appreciate it!
The app should skip files that already exist in the output folder (see screenshot).

Are you able to share a feed URL that you are having trouble with?

<img width="953" alt="Screenshot 2023-03-03 at 22 59 22" src="https://user-images.githubusercontent.com/6495600/222839517-7ae8288b-b064-4891-a04b-a51c0ca3d7aa.png">

**Comment by bennyrobinson** [comment]
Yep I'm an idiot, if you don't rename the output file to your own formatting it skips it...  Sorry about that. Definitely a User Issue there. Thanks again guys, Love it. 

Btw does the Linux version of this work on ubuntu do you know?

**Comment by freshe** [comment]
No worries 👍
If you're ok with compiling stuff it's easy to produce a binary for Ubuntu with GCC (apt install gcc).

g++ *.cpp -std=c++11 -O2 -lcurl -o poddl

If not, I can do it for you, just need to know what version you're using (22.04, etc)

**Comment by bennyrobinson** [comment]
No I'm not, I need to find out how to do it... I'm using 20.04.5

**Comment by freshe** [comment]
Got it, I've compiled a version for Ubuntu 20.04.
https://github.com/freshe/poddl/raw/master/bin/poddl-ubuntu-x64.zip

**Comment by bennyrobinson** [comment]
Thankyou
