### ISSUE TITLE
Suggestion: Halt at file found + reverse sorting

### ISSUE THREAD

**Issue by shpati** [freshe/poddl#9]
This is an excellent project @freshe, thank you for it!

Some features that I would like to see are:
1. Sort/number and download from newest episode to oldest, instead of from oldest episode to newest. 
Example: poddl.exe -r http://url.to.rss C:\OutputPath  (where -r stands for 'reverse order')
2. The ability for the program to stop downloading (not just skip) when the input next file contained in the rss contains a given string. Example: poddl.exe -h[string] http://url.to.rss C:\OutputPath (where -h stands for halt. If no string input is given than the program can just halt & exit anytime a file that already exists is found. Currently it skips that file and continues to download the rest of the episodes. 

The above would allow a user to download only the latest missing episodes (from newest to oldest) until the episode that was last downloaded is found in the given folder.

**Comment by freshe** [comment]
Thanks, appreciate it! Nice suggestions, will look into it soon 👍

**Comment by freshe** [comment]
I'm a bit confused about the -h option. Think you can clarify why you would want it to take a string argument? -h without arguments would stop when it finds the latest episode anyway right?

Thanks, @shpati

**Comment by shpati** [comment]
Yes, -h without argument would stop when it finds the first matching previously downloded episode. However it may be that the previous episodes may be already renamed to something else, for example some string or number may be replacing or appended to them thus not matching the original rss filename anymore. A 'halt at string found' condition could be useful in these cases if used in combination with a batch or bash script.

**Comment by freshe** [comment]
@shpati Thanks, I've created a branch where I've implemented these features (hopefully)
If you have time to try it out and see if it's what you suggested it would be helpful.

https://github.com/freshe/poddl/tree/reverse/bin

(argument -o for output path is now needed due to potential clash with -h)

**Comment by shpati** [comment]
It works great and as intended! Many thanks @freshe :)
The default use mode for me is: poddl.exe http://url.to.rss -r -h -o C:\OutputPath
It downloads episodes from the newest to the oldest until a previous episode is found. Then the program exits.

**Comment by freshe** [comment]
@shpati  Great! 👍
Thank you for testing, appreciate it!

**Comment by freshe** [comment]
Solved by 441ba82
